# Generated by Django 5.1.6 on 2025-04-01 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('product_title', models.CharField(max_length=255)),
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Other', 'Other')], max_length=50)),
                ('product_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('seller_phone', models.CharField(max_length=15)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('image1', models.ImageField(null=True, upload_to='item_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
