# Generated by Django 5.1.6 on 2025-04-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
